# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: eorer <marvin@42.fr>                       +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/11/07 16:17:25 by eorer             #+#    #+#              #
#    Updated: 2022/12/13 11:50:16 by eorer            ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

CC = gcc

CFLAGS = -Wall -Wextra -Werror -I.

NAME = libft_og.a

SRC = ft_atoi.c ft_isascii.c ft_isprint.c ft_memcpy.c ft_putnbr_fd.c ft_striteri.c ft_strmapi.c \
      ft_substr.c ft_bzero.c ft_isdigit.c ft_memmove.c ft_putstr_fd.c ft_strjoin.c \
      ft_strncmp.c ft_tolower.c ft_calloc.c ft_itoa.c ft_memset.c ft_split.c ft_strlcat.c \
      ft_strnstr.c ft_toupper.c ft_isalnum.c ft_memchr.c ft_putchar_fd.c ft_strchr.c ft_strlcpy.c \
      ft_strrchr.c ft_isalpha.c ft_memcmp.c ft_putendl_fd.c ft_strdup.c ft_strlen.c ft_strtrim.c

BONUS = ft_lstadd_back.c ft_lstadd_front.c ft_lstlast.c ft_lstnew.c ft_lstsize.c ft_lstdelone.c \
	ft_lstclear.c ft_lstiter.c ft_lstmap.c

OBJECTS = $(SRC:.c=.o)

BONUS_OBJECTS = $(BONUS:.c=.o)


all: $(NAME)

$(NAME): $(OBJECTS) $(BONUS_OBJECTS)
	@ar -rcs $(NAME) $(OBJECTS) $(BONUS_OBJECTS)

clean:
	@/bin/rm -f $(OBJECTS) $(BONUS_OBJECTS)

fclean:	clean
	@/bin/rm -f $(NAME)

re: fclean all

